Ab photogram industrial 2
aborov/photogram-industrial pull request #2
Opened 2024-06-29 19:35 UTC by aborov

2024-06-29 19:53 UTC, jniewiel approved these changes
Approved.

2024-06-29 19:56 UTC, aizatibraimova approved these changes
Looks good

2024-06-30 03:37 UTC, jniewiel approved these changes
Looks good.

2024-07-01 13:38 UTC, aizatibraimova approved these changes

2024-07-01 16:12 UTC, thierrychau requested changes
Please see comments below

2024-07-01 16:12 UTC, thierrychau commented on app/models/like.rb
> +  belongs_to :photo, counter_cache: true
Can you add a validation to prevent a user to like the same photo more than once?

2024-07-01 16:12 UTC, thierrychau commented on public/example_dev.rake
Any reason why there are two sample data methods? This one and lib/tasks/dev.rake

2024-07-01 16:32 UTC, aborov commented on public/example_dev.rake
This one is called example_sample_data, so it's not being run by `rake sample_data`, but thanks for the catch. I would like to keep it around for reference, so I just commented it out to be safe.

2024-07-01 16:33 UTC, aborov commented on app/models/like.rb
> +  belongs_to :photo, counter_cache: true
Sure! I just did with the recent commit.

2024-07-01 16:37 UTC, thierrychau approved these changes
Looks good, you can merge it. 

For future reference: let the reviewer resolve conversations

2024-07-01 16:38 UTC, merged